apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-root
spec:
  selector:
    matchLabels:
      app: vulnerable-root
  template:
    metadata:
      labels:
        app: vulnerable-root
    spec:
      containers:
      - name: vulnerable-root
        image: nginx:latest
        securityContext:
          runAsUser: 0 # root user
          privileged: true # privilege escalation
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
